### ISSUE TITLE
plaintext secret keys

### ISSUE THREAD

**Issue by ataberkcanitez** [bilginyuksel/digitivation#1]
Secret keys stored insecure way.
They should be encrypted or they should be removed from public repositories (maybe even for the private repositories)

Possible solutions:
 - Remove the secrets from properties, add them to `program arguments`
     ex: `--iyzipay.apiKey=xxx --iyzipay.secretKey=xxx`
 - You can create `secret.properties` file in the project and store this secret keys in there. Then you should add this file to `.gitignore` to keep this in your local.
 Also you should import this `secret.properties` to `application.properties` file by adding this line `spring.config.import=optional:secret.properties`
 - After the deployment, you should add those keys to `environment variables`

**Comment by bilginyuksel** [comment]
https://github.com/bilginyuksel/digitivation/pulls?q=is%3Apr+is%3Aclosed
